ALTER TYPE session_status ADD VALUE IF NOT EXISTS 'EXTRACTING';
ALTER TYPE session_status ADD VALUE IF NOT EXISTS 'EXTRACTED';

ALTER TABLE patterns
  ALTER COLUMN confidence_pct DROP NOT NULL,
  ALTER COLUMN confidence_pct DROP DEFAULT,
  ALTER COLUMN status DROP NOT NULL,
  ALTER COLUMN status DROP DEFAULT,
  ALTER COLUMN redirect_pct DROP NOT NULL,
  ALTER COLUMN redirect_pct DROP DEFAULT;
